POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "1234"
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
"username": "user2",
"password": "1234"
}
###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "12345"
}

### eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc4Mjc5NjcxOCwiZXhwIjoxNzgyNzk3MDE4LCJrZXkiOiJ2YWx1ZSJ9.St02NdnmROJuWy2JVhQB4w_cUD4en9KsIAF6qqcCSC2hxELn3AGhuW9CrmTXpoCL

GET http://localhost:8080/member/3
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc4Mjc5NjcxOCwiZXhwIjoxNzgyNzk3MDE4LCJrZXkiOiJ2YWx1ZSJ9.St02NdnmROJuWy2JVhQB4w_cUD4en9KsIAF6qqcCSC2hxELn3AGhuW9CrmTXpoCL

### 토큰없이 요청 보내기 -> CustomAuthenticationEntryPoint 에서 처리
GET http://localhost:8080/member/3


### 일반회원 토큰으로 admin 권한의 url에 요청 보내기
GET http://localhost:8080/security/admin
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTc4Mjc5OTM0NSwiZXhwIjoxNzgyNzk5NjQ1LCJrZXkiOiJ2YWx1ZSJ9.zD2Epcb8QsToKDn_yfCysATSIDi2NyjDOIIaTGMaFzkqG0Es2b831wmIY_n3I33F
